### ISSUE TITLE
uncatchable error

### ISSUE THREAD

**Issue by juliangruber** [segmentio/nsq.js#54]
Although I have an error listener in place, there's an unhandled error event. I'll investigate.

```js
var nsq = require('nsq.js');

var r = nsq.reader({
  topic: 't',
  channel: 'c',
  nsqd: ['n']
});

r.on('error', function(err){
  console.error(err.stack);
});
```

```bash
 ∴  node t
Error: n:4150: getaddrinfo ENOTFOUND n n:4150
    at errnoException (dns.js:25:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:75:26)
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: n:4150: getaddrinfo ENOTFOUND n n:4150
    at errnoException (dns.js:25:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:75:26)
 ∴  echo $?
1
```

**Comment by robertklep** [comment]
Bumping because I'm running into the same issue (`ETIMEDOUT` in my case).

**Comment by juliangruber** [comment]
possible fix: https://github.com/segmentio/nsq.js/pull/55

**Comment by robertklep** [comment]
@juliangruber yeah I saw :+1: just bumping the issue to get it merged ;-)
