### ISSUE TITLE
npm install nsq.js  error

### ISSUE THREAD

**Issue by zanjs** [segmentio/nsq.js#68]
```ssh

$ npm install nsq.js --save
npm WARN package.json curlnode@1.0.0 No description
npm WARN package.json curlnode@1.0.0 No repository field.
npm WARN package.json curlnode@1.0.0 No README data

> bignum@0.11.0 install E:\zan\coding\panli\curlnode\node_modules\nsq.js\node_modules\bignum
> node-gyp configure build


E:\zan\coding\panli\curlnode\node_modules\nsq.js\node_modules\bignum>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node  configure build )
▒ڴ˽▒▒▒▒▒▒▒▒һ▒▒▒▒▒▒һ▒▒▒▒Ŀ▒▒▒▒Ҫ▒▒▒ò▒▒▒▒▒▒ɣ▒▒▒▒▒ӡ▒/m▒▒▒▒▒ء▒
  bignum.cc
..\bignum.cc(413): warning C4244: ▒▒=▒▒: ▒ӡ▒double▒▒ת▒▒▒▒▒▒uint64_t▒▒▒▒▒▒▒ܶ▒ʧ▒▒▒▒ [E:\zan\coding\panli\curlnode\node_modules\nsq.js\node_modules\bignum\build\bignum.vcxproj]
  win_delay_load_hook.c
LINK : fatal error LNK1181: ▒޷▒▒▒▒▒▒▒▒ļ▒▒▒C:\OpenSSL-Win64\lib\libeay32.lib▒▒ [E:\zan\coding\panli\curlnode\node_modules\nsq.js\node_modules\bignum\build\bignum.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd E:\zan\coding\panli\curlnode\node_modules\nsq.js\node_modules\bignum
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nsq.js" "--save"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.11.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.11.0 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\zan\coding\panli\curlnode\npm-debug.log


```

**Comment by juliangruber** [comment]
the dependency that fails to compile is https://github.com/justmoon/node-bignum. we're using the latest version so the problem is either on their side or in your setup.

best create an issue here: https://github.com/justmoon/node-bignum/issues

**Comment by matteocontrini** [comment]
Would it be possible to stop using that particular bignum module? The fact that nsq.js has dependencies that need to be compiled makes the `actually written in js :p` statement wrong.

I started using this module instead of nsqjs because it's written in JavaScript but it's a pain to do an `npm install` on Windows, every single time.
